### PR TITLE
Themes config

### PR DESCRIPTION
**Pull request by boformer**
Added xml configuration for the themes.

TODO:
- Loading and Saving
- Compilation of the FastList for the getRandomBuildingInfo method

### CODE REVIEW

**Comment by boformer** [comment]
Oh great, the commits are messed up. Time to get a better git client.

**Comment by bloodypenguin** [comment]
`Oh great, the commits are messed up. Time to get a better git client.`
Atlassian Source Tree is my favorite.

**Comment by boformer** [comment]
@earalov Last time I tested my code there was a problem:

Enabling and disabling themes using the policy GUI works as expected, but the "getRandomBuildingInfo" method ignores the choice.

I wonder why.

**Comment by boformer** [comment]
BTW, I'm a java guy, so I'm familiar with Eclipse egit. 

Now I'm using Visual Studio for programming and Eclipse as a git client. Feels wrong, but works well for me :)

**Comment by boformer** [comment]
This is the result i am getting: http://i.imgur.com/ClHPnD0.jpg

left: euro district, right: int district

**Comment by bloodypenguin** [comment]
I'm Java guy too but I prefer IntelliJ IDEA. It's a shame that Jetbrains hasn't included their excellent versioning tool in ReSharper plugin for VS.

After including your recent GUI changes into my branch I don't see 'enabled theme' and 'disabled theme' messages in log. When I disable a theme for a district then switch to another district and then switch back  I see that the theme I disabled is marked is active. Looks like checkbutton's event just doesn't fire. Because of that both themes stay enabled for all districts and that's why buildings aren't filtered. Do you observe same UI behavior?

**Comment by boformer** [comment]
No, the GUI works for me. Look at the first line of the logger in the screenshot I posted.

I will try it when I get home.

**Pull request closed without merging**
