### PR TITLE
UI for Spawn Rate, Cloning and Upgrade features

### PR DESCRIPTION
**Pull request by SamsamTS**
Let me know what you think.

If everything works as intended, an update is recommended asap because of the bug fixes. Especially for issue #63.

EDIT: ~~I forgot about spawn rate, adding it asap (shouldn't take long).~~ Done

### CODE REVIEW

**Comment by boformer** [comment]
Testing...

**Comment by boformer** [comment]
One problem when editing mod themes:

Once you start editing things like spawn rate of a built in building, it is added to the user config:

``` xml
    <Theme name="American Trailer Homes">
      <Buildings>
        <Building name="437039049.DK-L1 2x2 Trailer House 2_Data" spawn-rate="11" />
      </Buildings>
    </Theme>
```

 When you then uncheck the "include" checkbox, it is removed from the user config:

``` xml
    <Theme name="American Trailer Homes">
      <Buildings>
      </Buildings>
    </Theme>
```

What is expected to happen:

``` xml
    <Theme name="American Trailer Homes">
      <Buildings>
        <Building name="437039049.DK-L1 2x2 Trailer House 2_Data" include="false" />
      </Buildings>
    </Theme>
```

That's the problem I was talking about all the time.

**Comment by boformer** [comment]
I will see if I can quickly rewrite the config system to fix that.

**Comment by SamsamTS** [comment]
Oh I see, when you uncheck the include box it is removed from the config, loosing other settings like upgrade or spawn rate. Which should be kept for the blacklist mode now that I think about it. Is that the issue?

I haven't thought about the blacklist mode until now so I didn't saw an issue with that. I'll see if I can fix that.

I'm on holidays for a week starting today, I'm planning on doing some cleanup/improvements, including reworking the configuration. I know you need to concentrate on your exams, just tell me the issues and I will work them out.

**Pull request merged**
